name: Bug Report
description: Report bug, crash, issue...
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of the problem:
    validations:
      required: true

  - type: textarea
    id: to-reproduce
    attributes:
      label: To reproduce
      description: |
        Explain step-by-step how to see the issue:
    validations:
      required: true

  - type: textarea
    id: error-log
    attributes:
      label: Error log
      description: |
        Find the error log from Blender, so we can track down the issue! **(This is the most important part of the bug report)**
        - On Mac or Linux:
          1. Close Blender and then open the Terminal app
          2. Run `cd /Applications/Blender.app/Contents/MacOS && ./Blender`
          3. Do whatever causes the bug
          4. Copy and paste the error you see in the Terminal
        - On Windows:
          1. In Blender, go to Window > Toggle System Console
          2. Copy and paste the error you see in the console window
        - [Get help](https://docs.blender.org/manual/en/3.3/advanced/command_line/launch/index.html)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment 
      description: |
        Please provide information about your operating system, version of Blender and AI Render, etc.
        
        AI Render version: in Blender, click on: `Edit > Preferences > Add-ons`, search for AI Render and expand it. This will show you the version of AI Render.
        Blender version: in Blender click on: `Blender Icon (upper left corner) > About Blender`. This will show you the version of Blender.
      value: |
        - Blender version (upper right corner of splash screen): 
        - AI Render version (find in Preferences > Add-ons): 
        - Operating system: (Windows, OS X, etc)

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/video
      description: |
        If applicable, please provide a screenshot/video of the problem.
    validations:
      required: false
      
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        Anything other helpful information to know?
    validations:
      required: false
